### ISSUE TITLE
Individual intersection size issue

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/upset-alt-txt-gen#66]
![Image](https://github.com/user-attachments/assets/700f96b8-e856-45fa-802b-1b125444aa84)

I'd argue that this isn't accurate, there's only one 

And here there's also only one and that's the 10th largest: 

![Image](https://github.com/user-attachments/assets/7e531642-5254-4322-8088-d2d875c55aee)

**Comment by elizaan** [comment]
So, after a lot of investigation, I can confirm what happened:
For organization data (first picture),

The values of data in large regions are 19 and 17. Here, 19 = individual set, and 17 = medium set. Now, in large data regions, 50% of the data is either an individual set or a medium set. Particularly for this reason, you are seeing individual sets being in large regions. I did a threshold of 50% for inclusion criteria in a particular region, but I can not think of any better percentage for inclusion criteria than now.

Maybe, instead of saying, "The individual set intersections are large in size," we can say
"The individual set intersections dominates the large sized intersections"?

**Comment by alexsb** [comment]
I think what you need to do here is calculate how many items are in the individual intersections in total, vs in those with more than 1 set. If that's more than 50% we should say dominates, but here these are < 10 %. 

And not sure whether the 50% are the right metric of course.

**Comment by alexsb** [comment]
Also, we can't say "the individual sets dominate" if there's only one individual set. If it were the biggest by far, then we should use singular "the individual set dominates".  But that's maybe too nuanced.
